services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: tabnews_user
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: tabnews_db
    ports:
      - "5432:5432"
